#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run the test suite with coverage and enforce coverage thresholds, but exclude accessibility tests
npm test -- --testPathIgnorePatterns=tests/accessibility --coverage --coverageThreshold='{"global":{"statements":75,"branches":70,"functions":75,"lines":75}}' 