name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
      
      - name: Run tests with coverage
        run: npm test -- --coverage
        env:
          NODE_ENV: test
          OPENWEATHER_API_KEY: mock-api-key-for-testing
          PORT: 3000
          RATE_LIMIT_GLOBAL: 100
          RATE_LIMIT_WEATHER_API: 30
      
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # optional
          fail_ci_if_error: false
          
  accessibility:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Start application in background
        run: |
          npm run dev &
          echo "Waiting for app to start..."
          sleep 10
        env:
          NODE_ENV: test
          OPENWEATHER_API_KEY: mock-api-key-for-testing
          PORT: 3000
          RATE_LIMIT_GLOBAL: 100
          RATE_LIMIT_WEATHER_API: 30
      
      - name: Run accessibility tests
        run: |
          mkdir -p tests/accessibility/reports
          mkdir -p tests/accessibility/screenshots
          # Allow accessibility test to fail but continue workflow
          npm run test:a11y || echo "⚠️ Accessibility tests failed but continuing workflow"
      
      - name: Upload accessibility reports
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-reports
          path: |
            tests/accessibility/reports/
            tests/accessibility/screenshots/ 